1. Convert List to 1D Array


In [2]:
import numpy as np

original_list = [12.23, 13.32, 100, 36.32]
arr = np.array(original_list)
print(arr)

[ 12.23  13.32 100.    36.32]


2. Create 3x3 Matrix (2?10)


In [5]:
import numpy as np

numbers = np.arange(2,11)
matrix = numbers.reshape(3,3)
print(matrix)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


3. Null Vector (10) & Update Sixth Value


In [7]:
import numpy as np

vector = np.zeros(10)
vector[5]=11
print(vector)

[ 0.  0.  0.  0.  0. 11.  0.  0.  0.  0.]


4. Array from 12 to 38


In [8]:
import numpy as np

arr = np.arange(12,39)
print(arr)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37 38]


5. Convert Array to Float Type


In [11]:
import numpy as np

arr = np.array([1,2,3,4])
arr_float = np.array([1,2,3,4],dtype=float)
print(arr_float)

[1. 2. 3. 4.]


6. Celsius to Fahrenheit Conversion


In [14]:
import numpy as np

centigrade = np.array([[0, 12, 45.21, 34, 99.91, 0],[-17.78, -11.11, 7.34, 1.11, 37.73, 0. ]])
fahrenheit = centigrade * 9 / 5 + 32
back_to_c = (fahrenheit - 32) * 5 / 9

print(fahrenheit)
print(centigrade)
print(back_to_c)

[[ 3.20000e+01  5.36000e+01  1.13378e+02  9.32000e+01  2.11838e+02
   3.20000e+01]
 [-4.00000e-03  1.20020e+01  4.52120e+01  3.39980e+01  9.99140e+01
   3.20000e+01]]
[[  0.    12.    45.21  34.    99.91   0.  ]
 [-17.78 -11.11   7.34   1.11  37.73   0.  ]]
[[  0.    12.    45.21  34.    99.91   0.  ]
 [-17.78 -11.11   7.34   1.11  37.73   0.  ]]


7. Append Values to Array (Do self-tudy)


In [15]:
import numpy as np

arr = np.array([10,20,30])
new = np.append(arr,[40,50,60,70,80,90])
print(new)

[10 20 30 40 50 60 70 80 90]


8. Array Statistical Functions (Do self-tudy)


In [17]:
import numpy as np

arr = np.random.rand(10)

mean_val = np.mean(arr)
median_val = np.median(arr)
std_val = np.std(arr)

print("Ramdom numbers: ",arr)
print("Mean:", mean_val)
print("Median:", median_val)
print("Standard Deviation:", std_val)



Ramdom numbers:  [0.94215403 0.54922218 0.8664237  0.43035936 0.00714708 0.67669446
 0.76196289 0.25404511 0.02991742 0.17174891]
Mean: 0.46896751409568765
Median: 0.4897907714085143
Standard Deviation: 0.3254809841735898


9 Find min and max


In [24]:
import numpy as np

arr = np.random.randint(0,100,(10,10))


print(arr)
print("Max value: ",arr.max())
print("Min value: ", arr.min())

[[18 52 76 18 50 96 20 88 46 18]
 [80 79 51 39 41 93 24 53 25 42]
 [61 51 86 86 74 91 58  7 23 18]
 [53 75 71 16 71 76 67 55 15 44]
 [49 99 43 12 56 12 64 91 28 42]
 [35 47 48 51 89 24 77 23 98  5]
 [28 25 89 22 72 67 18 47 53 62]
 [68 55 44 63  6 73 27 61 96 21]
 [33 20 91 79 14 98  1 91 57 41]
 [68 66 44 57 85 57 51  5 91 77]]
Max value:  99
Min value:  1


10. Create a 3x3x3 array with random values.

In [26]:
import numpy as np

arr = np.random.randint(0,10,(3,3,3))
print(arr)

[[[3 8 9]
  [7 7 5]
  [7 2 2]]

 [[6 3 2]
  [6 4 1]
  [4 5 4]]

 [[6 0 3]
  [7 2 0]
  [4 9 2]]]
